### ISSUE TITLE
Organisational Issues and tips

### ISSUE THREAD

**Issue by MateuszPodeszwa** [xamSemaj/Portfolio#2]
Hi, @xamSemaj

I’m glad to see you again working on your portfolio. I’d like to share some pro tips to help make your repository better for others.

- [ ] 1. Include a `.env-template` file.
- [ ] 2. Use concise commit messages that clearly explain the changes. You can provide more details in the commit description.
- [ ] 3. Always mention the file related to the code in the issue or commit message. This will help localize specific changes without having to look through the code.
- [ ] 4. Create a `README.md` file that explains the repository’s purpose, provides a brief description of the structure, includes information about the tech stack, and outlines how to install it along with all necessary setup steps.
- [ ] 5. Develop an issue policy and create templates for issues.
- [ ] 6. Create branches only when necessary, such as for specific issues or when you plan to make substantial changes to the project. For example, when upgrading to a newer version, installing a new package, or implementing significant functionality that could alter the code. Branches help maintain a clear separation between different versions of the code, and you can always merge them later.

**Remember less is better. A simpler and neater solution pays off, try to avoid complexity and keep your repo well-managed. You can check out my profile to see what bad-managed repo looks like and do the opposite :|**

**Comment by xamSemaj** [comment]
Thank you this is a completely broken repo anyway I was just trying to see what I could recover 😆
